### PR TITLE
Install moose-libmesh using conda

### PR DESCRIPTION
**Pull request by AI-Pranto-1**
<div align="center">

|  build_arg  |  Test  |
| :---: | :--- |
| DAGMC+libmesh | :heavy_check_mark: |
| DAGMC | :heavy_check_mark: |
| libmesh | :heavy_check_mark: |
| Normal | :heavy_check_mark: |

</div>

Here are a few updates - 
- Use `conda` to install `moose-libmesh` tool.
-  if `$build_libmesh=on`  manually install miniconda instead of pulling `continuumio/miniconda3` image because `make` command suddenly stopped compiling. Here’s the result after running the make command.
```bash
[  9%] Building CXX object CMakeFiles/libopenmc.dir/src/boundary_condition.cpp.o
[  9%] Building CXX object CMakeFiles/libopenmc.dir/src/dagmc.cpp.o
[  9%] Building CXX object CMakeFiles/libopenmc.dir/src/bremsstrahlung.cpp.o
[ 10%] Building CXX object CMakeFiles/libopenmc.dir/src/bank.cpp.o
[ 11%] Building CXX object CMakeFiles/libopenmc.dir/src/cell.cpp.o
[ 12%] Building CXX object CMakeFiles/libopenmc.dir/src/cmfd_solver.cpp.o
[ 13%] Building CXX object CMakeFiles/libopenmc.dir/src/cross_sections.cpp.o
Obtaining file:///root/OpenMC/openmc
  Installing build dependencies: started
```

### CODE REVIEW

**Comment by AI-Pranto-1** [comment]
Source install of libmesh was failing because of the `--disable-netcdf-4` and `--enable-hdf5` options due to incompatibility with `contrib/netcdf`, removing this flag solves the problem.

We now have two options.

### 1. Source install

<div align="center">

|  build_arg  |  Test  |
| :---: | :--- |
| DAGMC+libmesh | :heavy_check_mark: |
| DAGMC | :heavy_check_mark: |
| libmesh | :heavy_check_mark: |
| Normal | :heavy_check_mark: |

</div>

## 2. Conda install

<div align="center">

|  build_arg  |  Test  |
| :---: | :--- |
| DAGMC+libmesh | :heavy_check_mark: |
| DAGMC | :heavy_check_mark: |
| libmesh | :heavy_check_mark: |
| Normal | :heavy_check_mark: |

</div>

@Shimwell, Which one will be better?

**Comment by shimwell** [comment]
If the docker file already included conda (e.g. if it was based of the miniconda3 image) then I guess we would opt for a conda install libmesh as this would also save some compiling time.

However this dockerfile doesn't have conda in it already so I see you have had to install conda using the ```wget``` method and then this allows conda install of libmesh from the inl channel. I guess we end up with two python versions as a result (system python and the anaconda python)

```
conda config --add channels conda-forge
conda config --add channels https://conda.software.inl.gov/public
conda install moose-libmesh
```

I get the impression from the rest of the docker file that there is a preference to avoid conda. Shall we check with @pshriwise

So I would opt for number 1. Source install which is out of character for me as I'm normally keen on Conda

**Comment by AI-Pranto-1** [comment]
If we go with the source install of libmesh, we have to deal with one more issue: rendering output on the screen.  Here's the output,

image

**Comment by AI-Pranto-1** [comment]
@Shimwell problem is solved after switching from Ubuntu-based OS e.g.`20.04 and pop_os-21.04` to Debian-based docker image, e.g. `debian:bullseye-slim`. I choose `debian:bullseye-slim` because it does not contain any extra files which are necessary inside containers,  resulting in a smaller image size (~5.9 GB -> 2.98 GB).

**Comment by shimwell** [comment]
> @Shimwell problem is solved after switching from Ubuntu-based OS e.g.`20.04 and pop_os-21.04` to Debian-based docker image, e.g. `debian:bullseye-slim`. I choose `debian:bullseye-slim` because it does not contain any extra files which are necessary inside containers, resulting in a smaller image size (~5.9 GB -> 2.98 GB).

Interesting, I am happy with any base image. Perhaps that is the best way to go. We can merge and see what the reviewers say. I'm giving you access to this repo so feel free to merge whenever you like

**Pull request merged**
